### ISSUE TITLE
[btb] Contact blog overview

### ISSUE THREAD

**Issue by mikeveeckmans** [mikeveeckmans/Joombiz-projects#20]
http://testuwsite.be/btb/index.php/contact/west-vlaanderen
Image is not correct displayed , can this be done by CSS or do we have to resize the images ?

**Comment by designbengel** [comment]
It´s just a small css issue "img {max-width: 100%;}" i will add it into the less file - but the image is then quite small. Should the size remain like it is? So i will have change the width of the column as well...
no problem :)

**Comment by mikeveeckmans** [comment]
maybe force image to 75px max width ?

**Comment by mikeveeckmans** [comment]
just for this pages , because some will have lots of adresses

**Comment by designbengel** [comment]
Right now it´s 148px but the image is uploaded bigger so it´s overflowing. When i set img max-with:100% it will be 148px but... not good at all - the images shouldn´t be bigger then needed ;) 
![bildschirmfoto 2016-06-16 um 17 22 22](https://cloud.githubusercontent.com/assets/828371/16122349/fd42c908-33e6-11e6-9313-d1b0ae2d90fc.png)

**Comment by mikeveeckmans** [comment]
as in the screenshot it's ok ;-)

**Comment by designbengel** [comment]
fixed ;-)
