### ISSUE TITLE
Favicon created

### ISSUE THREAD

**Issue by designbengel** [mikeveeckmans/Joombiz-projects#21]
Can you check if you like the created favicons? :-)
http://realfavicongenerator.net/favicon_checker?ignore_root_issues=true#.V2Zni-aLTMU

**Comment by mikeveeckmans** [comment]
Not able to see...

[image1.PNG]
Sent from my iPhone

On 19 Jun 2016, at 11:36, designbengel <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you check if you like the created favicons? :-)
http://realfavicongenerator.net/favicon_checker?ignore_root_issues=true#.V2Zni-aLTMU

-

**Comment by designbengel** [comment]
Don´t see your attachment from iphone :)

**Comment by mikeveeckmans** [comment]
![2016-06-19_13-05-00](https://cloud.githubusercontent.com/assets/4589318/16176950/8baf6d84-361e-11e6-8c41-10dd2e3e6eb0.png)

**Comment by mikeveeckmans** [comment]
Oh ok ;-) 
i see the favicons are already added to the site ;-) yes they're good ;-)
