### ISSUE TITLE
[antaxius] K2 layouts - change

### ISSUE THREAD

**Issue by mikeveeckmans** [mikeveeckmans/Joombiz-projects#25]
EG item view : http://www.testuwsite.be/antaxius/index.php/nl/over-ons/team/item/17-yannic-van-landeghem

EG tags view : http://www.testuwsite.be/antaxius/index.php/nl/over-ons/partners

Item view : picture on the left , text next to the picture , additional info directly under text (need to translate that :-P )

Tags view : picture smaller , maybe 2 columns? read more as button ?

**Comment by designbengel** [comment]
partly solved :)

**Comment by designbengel** [comment]
I think i forgot to close it, should be solved?
