### ISSUE TITLE
[btb] breadcrumb issue

### ISSUE THREAD

**Issue by mikeveeckmans** [mikeveeckmans/Joombiz-projects#26]
http://www.testuwsite.be/btb/index.php/9-article-showcase/3-lorem-ipsum-dolor-sit-amet-10-maart-2016
![2016-06-22_19-33-42](https://cloud.githubusercontent.com/assets/4589318/16276831/5f81a418-38b0-11e6-83b4-2e63426b0fba.png)

**Comment by designbengel** [comment]
Don´t know, i had to revert all the .less files today maybe it´s a issue with this... :) will fix it asap

**Comment by designbengel** [comment]
Breadcrumbs fixed by linking Nieuws to the Category News ;)
