### ISSUE TITLE
[btb] woord van de voorzitter module home

### ISSUE THREAD

**Issue by mikeveeckmans** [mikeveeckmans/Joombiz-projects#28]
cfr news , woord vd voorzitter cat , above bottom

**Comment by designbengel** [comment]
what is needed here? thx :)

**Comment by mikeveeckmans** [comment]
Had to think a bit :-P 
Would it be possible to create ( just as the newsslider) a module under the current content with input from the "woord van de voorzitter" category ?

**Comment by designbengel** [comment]
Done, but we need to think about 1) truncation the introtext so that the box doesn´t change the height 2) set a minimum height of the box or 3) take care that introtext is not longer then xy chars...
